spring:
  application:
    name: edutrack

  config:
    import: "optional:configserver:http://config-server:8888"

  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        max-interval: 8000

    discovery:
      enabled: true
